- .gitignore
- .shopify-cli.yml
- package-lock.json
- package.json
- pages/hi.js
- scripts/billing/generate-one-time-charge.js
- scripts/billing/generate-recurring-billing.js
- scripts/index.js
- scripts/tests/generate-billing.test.js
- scripts/tests/generate-webhooks.test.js
- scripts/tests/server-mocks.js
- scripts/tests/utilities.test.js
- scripts/transform.js
- scripts/utilities.js
- scripts/webhooks/generate-scopes.js
- scripts/webhooks/generate-webhhoks-subscription.js
- scripts/webhooks/generate-webhooks-environment.js
- scripts/webhooks/generate-webhooks.js
- server/handlers/client.js
- server/handlers/index.js
- server/handlers/register-webhooks.js
- server/server.js
This adds the ability to create create webhooks subscriptions and receive webhooks.
This work assumes that the cli will run: `npm run-script generate-webhooks WEBHOOKS_TOPIC`
At this time, I have hardcoded a scope for the array as I'm not sure how we're planning passing it to the command line. We could just pass it as an arg to the script like the `TOPIC`. 
The app will generate the URLS through the [createWebhooksUrl](https://github.com/Shopify/webgen-embeddedapp/compare/add-webhooks?expand=1#diff-0c58aff4abebd9398603910227ca8db6R4) helper.
This PR also updates the [server](https://github.com/Shopify/webgen-embeddedapp/pull/18/files#diff-ea75b530d74f94670cea053feb8b961bR44) to handle routes with `verifyRequest`
Last thing, moved some files around into subfolders and put a bunch of …
> Add webhooks generation 

- scripts/billing/generate-one-time-charge.js
- scripts/billing/generate-recurring-billing.js
- scripts/tests/generate-billing.test.js
- scripts/tests/generate-webhook.test.js
- scripts/tests/server-mocks.js
- scripts/transform.js
- server/server.js
This is a fix for the billing command, it was checking for the `ctx.redirect` node, but if a user had already run the command, that node doesn't exist. Now it replaces the existing handler with the new one. 
I plan on jazzing this up a bit when I do my node app jazz work. I just wanted to fix this for anyone testing commands right now.
> Fix billing

- package-lock.json
- package.json
this pr:
* moves @babel/core, @babel/register, and @babel/polyfill out of `devDependencies` and into `dependencies`
* adds isomorphic-fetch as an explicit dependency
these changes are required for the app to run correctly in a prod env
> move some deps out of dev

- scripts/page/generate-page.js
When I was testing Tyler's branch I noticed if the user passed a cased name it would create a file with that way, which is annoying for routes.
> ensure filename is lower case

- server/handlers/client.cli.js
- server/handlers/client.js
As per @nwtn this seems like the best way to get the `npm package version` for the user agent.
> add user-agent

- package-lock.json
- package.json
- pages/_app.js
- server/server.js
afterAuth forces redirect to '/' which causes errors if the page is loaded outside of Shopify Admin.
MyApp is expecting shop to be available as a query parameter and thus causes an exception on the front end once the app is installed.
In order to fix this I set the shop as a cookie which is accessed by MyApp
> Fix - forceRedirect only works if shop is in query parameters

- package-lock.json
- package.json
Fixes https://github.com/Shopify/shopify-app-cli/issues/895 
It's been reported that the node boilerplate code is failing in production with the current version of koa-session, and bumping it to the latest version fixes that issue.
Bumping `koa-session` to 6.0.0.
> Bump koa-session to v6.0.0

- package-lock.json
- package.json
Fixes #476 
We're still naming this package as per the old repo name in `package.json` and the lock file.
Updating the repo name in those files.
> Fix repo name references

- package.json
`lint-staged` now automatically adds any changes to the original commit, making `git add` superfluous (as stated by their own warning).
_Fixes nothing._
Updated package.json `lint-staged` hook.
> Remove superfluous git add from lint-staged hook

- package-lock.json
- package.json
- pages/_app.js
This app is set to be embedded by default, so we should make sure that the client side is equipped to make JWT-based requests from the get-go.
Adding `app-bridge-utils` so we can leverage `authenticatedFetch` in our App component, which abstracts all of the logic of setting up the session token. With this, requests to the server will include the `Authorization: Bearer XYZ` header and therefore transparently enable these requests to match to the current session.
> Add authenticatedFetch to React App by default

- package-lock.json
- package.json
- server/server.js
The new library will add its own functions to set up a GraphQL proxy, so we will no longer need to import the package. Once that feature is available, we should add it back under the new format.
Simply removes the package and its use from the app.
> Remove GraphQL proxy package

- package-lock.json
- package.json
- server/server.js
The current implementation of the app still relied on 3rd party cookies for the initial `/` load to fetch the app skeleton, which still caused it to fail if one attempted to reach the app by clicking the Admin link to it.
I added an sqlite database to the app so we can store the shops to which it's been installed. Since we now have a means of persisting data, I also went ahead and added a `CustomSessionStorage` object which also leverages it to provide persistent sessions.
> Use unauthenticated root path

- package-lock.json
- package.json
- server/server.js
The `koa-shopify-auth` package now brings `shopify-api` along with itself, which means we no longer have to initialize two copies of the library.
Removing the direct dependency on the library which no longer makes sense, since it's brought along as a top-level package by `koa-shopify-auth`.
> Remove secondary koa init

- package-lock.json
- package.json
The Koa library was updated to ensure we're always sending the proper user agent, this is just bumping that dependency to make sure we're using it.
> Bump koa-shopify-auth dependency

- package-lock.json
- package.json
This PR just bumps `koa-shopify-auth` to the latest version, which fixes issues with offline tokens.
> Bump koa-shopify-auth version

- next.config.js
In `shopify/quilt`, we updated our package builds to provide an [ESM build](https://github.com/Shopify/quilt/pull/1698) for consumers. This provides apps with more tree-shakable builds resulting in smaller production builds. Internally, our tooling is already configured to support these builds, though this boilerplate app isn't (see https://github.com/Shopify/quilt/issues/1722). 
Fixes https://github.com/Shopify/quilt/issues/1722
Adding out of the box support for ESM (`.mjs` files) libraries (Packages living in `shopify/quilt`)
> Add ESM support for .mjs files in the nextjs config 

- next.config.js
- package-lock.json
- package.json
When this app started running, we always logged
```
Warning: Built-in CSS support is being disabled due to custom CSS configuration being detected.
```
That call is no longer needed since it was deprecated by next, stating:
```
Next.js now has built-in support for CSS: https://nextjs.org/docs/basic-features/built-in-css-support. The built-in support solves many bugs and painpoints that the next-css plugin had.
```
Dropping the deprecated call.
> Remove unnecessary withCSS call

- package-lock.json
- package.json
- pages/_app.js
- server/server.js
`@shopify/koa-shopify-auth` added support for returning a header indicating the auth URL to redirect to instead of the `Location` header, so that the GraphQL proxy (and other XHR requests) can also trigger the OAuth flow when a session expires.
Toggling the feature to return a header on, and wrapping the `authenticatedFetch` in a custom function that looks for the presence of that header and triggers an App Bridge redirect to it.
> Handle redirect header on proxy requests

- package-lock.json
- package.json
Bumping `koa-shopify-auth` to the latest version which stops using the `SameSite=none` setting altogether for cookies.
> Bumping koa-shopify-auth

- server/server.js
Related to #311
Related to #76
The current routing setup results in users being redirected to the app root when the app is reloaded (regardless of what path the user is currently on).
This pull request replaces the routing logic for all pages with the current routing logic for the root page, which will prompt a user to go through OAuth if there is no current session, but will redirect them to the current context afterwards.
cc @paulomarg
> Fix redirection inconsistency and simplify routing for "multi-page" apps

- package-lock.json
This PR bumps the `koa-shopify-auth` package to its latest version.
> Bump koa-shopify-auth to v4.1.4

- README.md
The CLI has been slightly rebranded from shopify-app-cli to shopify-cli
> Update Shopify CLI name

- server/server.js
Fixes #644 
This change allows for both patterns with a trailing slash and patterns without a trailing slash.
An example is shown below.
```
$ node --version
v16.5.0
$node
> "https://sampleapp.herokuapp.com/".replace(/https:\/\/|\/$/g, "")
'sampleapp.herokuapp.com'
> "https://sampleapp.herokuapp.com".replace(/https:\/\/|\/$/g, "")
'sampleapp.herokuapp.com'
```
> Fix HOST environment variable parser (#644)

- .github/workflows/ci.yml
- .github/workflows/merge_patch_dependencies.yml
- server/__tests__/server.test.js
Polaris v9 drops support for node v14 and it will soon be out the maintenance window anyway. Also tidying up the auto-merge patch workflow.
> fix CI workflows

- package.json
- yarn.lock
Fixes #0000 
The current version of Vite in this project has a bug where when changes occur in the API behind a proxy (as in our case here), Vite pings the dev server to check the connection which is momentarily not running and throws an uncaught exception.  This requires a manual refresh of the page which looks like this in the Shopify Admin:
This was making it difficult to extend the API in the app.  I was constantly manually reloading the page.
This updates Vite from `2.8.6` to `2.9.1` to incorporate these changes: https://github.com/vitejs/vite/pull/5466 which address this issue.  The API still reloads and goes through the auth process, but the manual refresh is no longer needed. :) 
This doesn't violate any peer dependencies
> Update vite to fix client pinging behind a proxy on WS disconnect

- server/__tests__/server.test.js
- server/helpers/top-level-auth-redirect.js
- server/index.js
- server/middleware/auth.js
The app was still using the old `shopOrigin` parameter for AppBridge. 
This PR switches out that old parameter for the new `host` one. Requires some additional passing around.
> Forward all query parameters during app install flow

- server/__tests__/server.test.js
- server/index.js
Fixes #800
Adds a header sent check to the default webhook handler, to avoid crashes when Webhook processing has already sent a response.
> Add header sent check to webhook handler

- .npmrc
Using `pnpm dev` to do a local deployment resulted in some files (within `node_modules/.pnpm`) not being found (returning `404` to FE).
Adds `shamefully-hoist=true` to support `pnpm`, in combination with https://github.com/Shopify/starter-react-frontend-app/pull/71
> Fix: Adds setting needed for pnpm dev to work

- web/.dockerignore
- web/Dockerfile
Adding `.dockerignore` for `node_modules` and `dist` allows removal of `rm -rf` commands from `Dockerfile` which enhances build speed.
☝🏻
> Add .dockerignore to speed up build

- .github/workflows/ci.yml
CI workflow is configured to only run on `main` branch
Change `main` to `cli_three` branch for CI workflow, and remove yarn cache (not needed here)
> Add cli_three to ci workflow

- web/middleware/auth.js
We currently let the warning about GDPR webhooks through when completing OAuth and setting up webhooks, which can be a bit confusing since there is no actual error.
This PR simply applies the suggested code to silence the warning messages for those webhooks.
> Omit GDPR webhook warnings

- web/__tests__/server.test.js
- web/index.js
- web/middleware/auth.js
- web/package.json
`README.md` file indicates that this template should create/use a `database.sqlite` file - however, template was set up to use memory session storage.
- Change session storage to SQLite
- Also changed references to starter-node-app to shopify-app-template-node
> Change session storage to SQLite

- .dockerignore
- Dockerfile
- web/.dockerignore
- web/docs/fly-io.md
- web/docs/heroku.md
To remove friction in the user guide - changing directories for hosting deployments and CLI use
- Moves the `Dockerfile` and `.dockerignore` files up a level
- Changes the instructions accordingly
> Move docker files up one level

- README.md
`npm init` caches heavily, hence need to force it to get the latest version
Change the `npm init @shopify/app` to `npm init @shopify/app@latest`
> Fix npm init command

- CHANGELOG.md
- README.md
- web/__tests__/server.test.js
- web/helpers/__tests__/ensure-billing.test.js
- web/helpers/__tests__/product-creator.test.js
- web/helpers/product-creator.js
- web/index.js
Current guidance is to prefer offline to online session tokens
Closes https://github.com/Shopify/first-party-library-planning/issues/355
- Change any reference to `online` from `true` to `false`
- Remove GraphQL proxy capability (requires online session tokens)
- Change `/api/products-count` to `/api/products/count` (aligned with change in frontend)
- Add `/api/products/create` endpoint for frontend (FE previously used GraphQL proxy)
> Switch to offline session tokens

- .github/workflows/ci.yml
- web/__tests__/server.test.js
- web/helpers/ensure-billing.js
- web/package.json
CLI 3 supports Node version 14, whereas this template specifies Node 16 as the minimum engine.
Downgrade Node engine requirement from 16 to 14 to align with CLI.
> Drop node to v14 in supported engines

- README.md
- web/index.js
Use of `express.json()` middleware must occur after processing webhook requests with `Shopify.Webhooks.Registry.process()`.
Add some documentation about ☝🏻
> Add note regarding express.json middleware

- server/index.js
- src/App.jsx
When `USE_ONLINE_TOKENS` is being set to `false` (to use offline tokens), then the app will crash as `loadCurrentSession()` takes `true` as a third argument which is `isOnline` parameter. It may lead to some confusion. Of course, it can be changed manually but `Shopify.Utils.loadCurrentSession(...)` should rely on global variable from `app.get("use-online-tokens")`
Changes hardcoded `true` value for `isOnline` param to global variable from `app.get("use-online-tokens")`
Second commit: also using `location.href` instead of `location` is more correct as `new URL(input[, base])` takes `string` as a first param.
> Set `isOnline` param based on global `use-online-tokens` value

- web/helpers/top-level-auth-redirect.js
- web/index.js
- web/middleware/auth.js
- web/middleware/verify-request.js
- web/package.json
If we get malformed shop names in the query args, we're currently still trying to use them, even though it's bound to fail when we reach Shopify.
Improving our sanitization of the arguments we receive, and properly escaping them when embedding them in strings.
> Improve query argument sanitization

- web/helpers/product-creator.js
The GraphQL client query method now throws an error if the server returns an error.
Note this depends on the merger and release of https://github.com/Shopify/shopify-api-node/pull/431
Template component of https://github.com/Shopify/first-party-library-planning/issues/385
Updates the `productCreator` method to handle this and to generate a meaningful error message.
> Add error handling to productCreator

- .gitignore
- web/index.js
There was a scenario in production where we could end up on a redirect loop if the production DB got wiped, but Shopify still thinks the app is installed (unlikely but you never know).
We would redirect to `/exitiframe` upon learning that we needed to break out of the iframe, which in production gets rendered by the `/*` route, which would trigger another redirect.
Letting requests to `/exitiframe` go through to the client-side where it'll get properly rendered by the React app.
> Fix infinite loop issue in production

- .github/workflows/close-waiting-for-response-issues.yml
- .github/workflows/remove-labels-on-activity.yml
- .github/workflows/stale.yml
Working on https://github.com/Shopify/first-party-library-planning/issues/458
This PR adds two new labels "Stale" and "Waiting for Response". Stale will be added to any issue that hasn't had activity for 90 days. If an issue is labeled as "Stale" and dose not have activity for an additional 14 days it will be closed automatically. The "Waiting for Response" label is added manually to an issue, if one of our devs is waiting for clarifications on a ticket. If the ticket doesn't see activity for 7 days it will be closed automatically. If it does see activity then the label is removed automatically.
> Adds "Stale" and "Waiting for Response" labels

- web/helpers/product-creator.js
Fix the product creation failure scenario handling, that currently leads to the current error being logged.
```
Failed to process products/create: ShopifyErrors is not defined
```
Fixes #0000
> [CLI_THREE] Fix product create error handling

- README.md
Noticed a broken link in the README.
Changes the link.
It was previously a "Getting Started" page (from [Internet Archive](https://web.archive.org/web/20210224225825/https://shopify.dev/tools/app-bridge/react-components))
and so I linked to the new "Getting Started" page.
> Fix broken link to App Bridge React in README

- web/package.json
Trailing comma causes `yarn install` to fail.
> Remove trailing comma

- .github/workflows/stale.yml
Issues that were closed by our stale workflow were getting closed as "complete". This might be confusing so we should close as `not_planned`.
[We are also doing this in `shopify_app`](https://github.com/Shopify/shopify_app/pull/1582)
> Add `not_planned reason` to Stale Workflow

- web/index.js
In development mode, the frontend runs on a separate process, and proxies requests to the backend.
By default, that only happens for paths under /api, under the assumption that the app is a single-page application. When adding backend routes outside that path, it's important to remember that we need to add proxy exceptions too, or the FE will take over and render the react app in development.
This PR adds a comment to the index file to help remind folks about the proxy rules.
> Add proxy instructions for non-API routes

- web/package.json
`@shopify/shopify-app-express@2.1.1` released
Updating the dependencies to be the latest
> Update to app_express 2.1.1

- .github/workflows/ci.yml
- web/package.json
* Node 14 has been EOL for a while, and our libraries [removed support from months ago](https://github.com/Shopify/shopify-app-js/pull/459).
* Node 16 is also currently EOL but we are currently still supporting it, so `--ignore-engines` flag was added to get our [CI passing again](https://github.com/Shopify/shopify-app-template-node/actions/runs/8087252698/job/22098773560?pr=1319).
* Looks like we [previously were on Node 16](https://github.com/Shopify/shopify-app-template-node/pull/941/files) on the template so no updates are necessary.
This was tested by creating a new app with the CLI using this branch as the template.
> Remove node 14 from CI and min dependency

- web/index.js
As part of [updating the template to use App Bridge React v4](https://github.com/Shopify/shopify-frontend-template-react/pull/255), we'll need to include the api key in the `index.html` file, which is served by the backend of the app.
Vite will handle replacing it in client-side renders, which is why the variable needs to start with a `VITE_`.
Dynamically replacing the api key when serving that file.
> Fix server-side rendering for App Bridge v4

- README.md
Fixes [How to Fetch POST or GET API with Shopify Auth After Hooks Folder Removal](https://github.com/Shopify/shopify-frontend-template-react/issues/299)
After the [migration to App Bridge 4](https://shopify.dev/docs/api/app-bridge/migration-guide#other-hooks), these templates no longer use custom hooks. But instead use automatic authentication with App Bridge.
* Updates the readme
> [Docs] Update readme to remove information about custom hooks
