Shopify/shopify-app-template-node

- scripts/index.js
- scripts/page/generate-page.js
- scripts/page/page-template.js
- scripts/tests/generate-page.test.js
Adds a nice template when people create a page. I didn't want to add too much stuff, as most people will just delete it automatically, but I wanted it to help the user a bit more and look nicer.
Closes #26
> adds template page for pages

- package-lock.json
- package.json
- pages/_app.js
- server/server.js
Adds proxy to make client side queries, as well as the client that's passed down to child components via the app. 
closes #25
> Add proxy and apollo client

- pages/_app.js
Adds the forceRedirect prop to the provider.
> add forceRedirect to provider

- .env.example
- .github/CONTRIBUTING.md
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- package.json
- pages/_app.js
- scripts/billing/generate-one-time-charge.js
- scripts/billing/generate-recurring-billing.js
- scripts/tests/generate-billing.test.js
- scripts/tests/generate-page.test.js
- scripts/tests/generate-webhook.test.js
- scripts/tests/transform.test.js
- server/handlers/index.js
- server/server.js
Adds contributing.md and updates readme. 
I'd love some feedback on the readme.
I also put things in alphabetical order.
> adds contributing md and cleans up files

- server/server.js
Updates the server to read the scopes set by user/CLI in env
> update server to use scopes from env

- scripts/page/generate-page.js
- scripts/transform.js
Exits and adds errors to generation.
> handle errors

- scripts/tests/utilities.test.js
- scripts/utilities.js
Fixes issue: https://github.com/Shopify/shopify-app-cli/issues/188
> check casing for component names

- package-lock.json
- package.json
Updates the `package.json` to include the newest version of the koa-auth package with installation fixes.
> update koa auth package

- package-lock.json
- package.json
- server/handlers/client.cli.js
- server/handlers/client.js
- server/server.js
Updates to newest version of our API. I will merge after my [change](https://github.com/Shopify/quilt/pull/1080) in the Quilt repo is merged.
> add new version

- server/handlers/register-webhooks.js
I updated the webhook package to accept a version and this needs to be updated to accept it.
> adds version to webhook registration

- package-lock.json
- package.json
Reverts Shopify/shopify-app-node#63
> Revert "Bump react-apollo from 2.5.8 to 3.1.3"

- server/handlers/register-webhooks.js
Using short notation for consistency. Was already suggested in https://github.com/Shopify/shopify-app-node/pull/51
> Small update to register-webhooks.js

- .dependabot/config.yml
> Change Dependabot update frequency to weekly

- README.md
Fixes https://github.com/Shopify/shopify-app-node/issues/418
> Fix link for Shopify App Bridge React

- package-lock.json
- package.json
- server/server.js
When bumping the version of `koa-router` to 9.0.0+, we were running into this error:
```
UnhandledPromiseRejectionWarning: TypeError: Unexpected MODIFIER at 0, expected END
```
That issue was actually caused by the way we set up our verification of requests in the server.
Essentially the same as https://github.com/Shopify/shopify-demo-app-node-react/pull/245, as per https://github.com/koajs/router/issues/76.
> Bump koa-router and fix route setup

- .github/workflows/triage.yml
Adding a dummy workflow file, to be modified on GitHub with actions for adding to Triage column in project board.
Adding `.github/workflows/triage.yml`
> Add a dummy workflow file

- package-lock.json
- package.json
- server/server.js
It updates the dependency on the new library and fixes changed calls.
> Bump API library version

- package-lock.json
- package.json
- server/server.js
The latest release of the library changed how we handle webhooks, so we needed to update our own code.
Using the latest webhook code, which handles parsing the request body for us.
> Updating webhook handling

- server/server.js
Fixes [Shopify-App-CLI#1104](https://github.com/Shopify/shopify-app-cli/issues/1104)
- Adds `/graphql` route to `server.js` to handle FED GraphQL requests
> Add /graphql route for FED requests

- package-lock.json
- package.json
Bumping the `koa-shopify-auth` dependency.
> Bumping koa-shopify-auth

- client/_app.js
- package.json
Part of https://github.com/Shopify/first-party-library-planning/issues/15
Upgrading the retired apollo packages
🎩 'd, looks good on my end
> Use @apollo/client

- .eslintignore
- .eslintrc.js
- .stylelintignore
- .stylelintrc.js
- package-lock.json
- package.json
- pages/index.js
- removing unnecessary configuration from the sample app eslint.
> simplify eslint config

- .github/workflows/merge_patch_dependencies.yml
> Enable auto-merge of patch depedencies

- .github/workflows/merge_patch_dependencies.yml
Run was failing without this: https://github.com/Shopify/shopify-app-node/actions/runs/1959213293
> Set `runs-on` for Action

- package.json
- yarn.lock
This PR updates the shopify-api library dependency from the RC to the real v3 🎉
> Update shopify-api to v3.0.0

- server/__tests__/server.test.js
~~I want to see if there's a better solution than simply turning up the timeout...~~
Having re-run the actions 3x for a total of 6 runs, I think this is working well. Open to any suggestions!
> use concurrency for production mode test

- .github/workflows/merge_patch_dependencies.yml
> revert to using the rest api as suggested for auto-merging passing patches

- server/__tests__/server.test.js
Since we're seeing consistent timeouts at 10s.
> chore: increase timeout for production mode test

- Dockerfile
- web/Dockerfile
> Updates Dockerfile to work with fly and Heroku

- .github/workflows/ci.yml
CI is limited to specific branches
Update CI to run on _**all**_ branches
> Fix: Run CI on all branches

- server/index.js
- src/App.jsx
This is just replicating the changes from #895 in this branch.
> Use online token setting for product count

- README.md
Now that the CLI's reverse proxy supports multiple WSS connections, this template can start doing Hot Module Reloading on that same WSS connection, which means we can have top-of-the-line reloading for both Safari and Firefox as well.
Updating the FE component, which now allows HMR on Firefox and Safari. It also adds the react plugin to the vite config, which enables us to reload each individual components as they're updated, resulting in a much better experience for all browsers 🎉
> Use WSS for HMR

- .github/workflows/ci.yml
- .gitignore
- web/helpers/product-creator.js
We shouldn't ignore lock files in the templates
- Remove lock files from `.gitignore`
- To avoid adding an undesired lock file to this repo, I added a new step on CI that checks that no lock file is present
> Remove lockfile from gitignore

- README.md
- web/package.json
- web/shopify.js
Update template to use SQLite session storage package
> Update template to use session storage packages

- SECURITY.md
> Fix spelling on SECURITY.md

- web/package.json
This dependency is never used, so we can just remove it.
> Remove jsonwebtoken dependency

- web/package.json
- web/shopify.js
Update `package.json` to use API v7
- not applicable ~I have added/updated tests for this change~
- not applicable ~I have made changes to the `README.md` file and other related documentation, if applicable~
> Update package.json to use API v7

- web/gdpr.js
- web/index.js
Closes #1262 
VSCode currently shows some warnings on a fresh repo.
Addressing those warnings.
> Fix warnings in fresh repo

- README.md
Translating apps is technically challenging, time-consuming, and costly. Despite the high demand for localized apps internationally, only a small fraction of apps offered in the Shopify App Store are translated. 
None of Shopify's app templates are localized, meaning that the full burden of responsibility is on the developer to research and implement an i18n framework for their app. It’s also more likely to be an afterthought until the developer decides to expand internationally, at which point the effort to externalize all the app's strings is much higher.
By localizing the default Node app template, we reduce the toil for developers, and set them up to localize their apps from the start.
- Update the front end app template to be internationalized (more details in [this pull …
> Internationalize Node app template

- web/package.json
This PR just updates the dependencies on the `@shopify` packages to the latest versions.
> Update shopify package dependencies

- README.md
`shopify-api-js` repository restructure folder. Old link not work anymore.
Change link in README.md
> Fix link to SessionStorage adapter guide

- web/index.js
- web/privacy.js
This PR is a part of an [overall Shopify directive](https://github.com/Shopify/trust-partnerships/issues/290) to remove any privacy regulation-specific terminology from Shopify's codebase in favor of privacy language that is more generalized.
* Replacing references of `GDPR` with `privacy`
> Rephrashing GDPR terminology in Shopify/shopify-app-template-node

- .github/workflows/ci.yml
* We no longer support node 16
> Remove Node 16 workflow
